### ISSUE TITLE
Legend Doesn't Load 

### ISSUE THREAD

**Issue by Nick-t-go** [Esri/angular-esri-map#272] opened 2016-04-14 19:37 UTC
I want to display a legend.

#### Actual behavior

The legend doesn't load. Instead the whole screen is blocked by an empty element, once there is a scroll the map reappears minus the loaded feature layers and legend.

#### Steps to reproduce the behavior

Here is a link to the plunkr showing the problem. The error occurs since I have loaded the Legend. Take legend directive off to see normal functionality. 

https://plnkr.co/edit/nP5DLkbhfbbQW49iief8?p=preview

**Comment by jwasilgeo** [comment] 2016-04-14 20:18
@Nick-t-go, the legend you'd like to construct this way just needs one more line in your HTML.  You can think of it as something that needs 2 pieces to be constructed.  Add something like the following line to where you actually want the legend to show up (this worked for me in your example):

`<div id="legend"></div>`

Also, you won't need to `require` in that module in the JS.

The **Description** section [here](https://arcgis.github.io/angular-esri-map-site-v1/docs/#/api/esri.map.directive:esriLegend) outlines the requirements for both a directive to communicate with a parent map directive, and an element to render the legend in.

I will close this now, but let me know if you still encounter any issues.

**Closed by jwasilgeo** 2016-04-14 20:18 UTC

**Comment by Nick-t-go** [comment] 2016-04-14 20:51
Yea that does work but not sure why I didn't understand that from just looking at the docs.  A few things about doing this legend this way.\

 It doesn't respond to changes in rendering when I use the `redraw` method unless I move the map(pan or zoom). Also this doesn't seem very angular-esque relying on this widget makes it difficult to make it more intractable. I'll have to research how to add toggles and offer users a color picker and such.  I'd like to suggest making a more Angular motivated 2-way binding motivated, friendlier legend directive. Perhaps I'll work on one myself once I get all the pieces in order. Thanks for your help @jwasilgeo

**Comment by jwasilgeo** [comment] 2016-04-14 23:27
Great to hear its working for you as intended, @Nick-t-go. In the end, it _is_ the Esri JSAPI 3.x Legend widget. If you want to create your own directive with your own custom features, definitely go for it! This repo is well-suited to help you on your way and give you a place to extend from.

You may also be interested in @Kollibri's https://github.com/Kollibri/angular-esri-map-toc.

I also should mention that this repo isn't necessarily intended to host additional custom directives. If you make such a directive, we encourage you to share it the way @Kollibri did. Also check out some recent [presentations](https://github.com/Esri/angular-esri-map#resources) and the [Patterns](https://arcgis.github.io/angular-esri-map-site-v1/#/patterns) docs that touch on this as well.
