### ISSUE TITLE
Legend do not reload after changing to different /route and returning to map.

### ISSUE THREAD

**Issue by jmrroy** [Esri/angular-esri-map#129] opened 2015-10-19 13:20 UTC
Hi,
I have an app with many factories, that use a map with same layers. When I go to the detail of a factory, I display an automatically centered map with the lat long values stored in the database with different layers.
My problem is that legend load only once, when I go back an choose an other factory the legend don't reload (it is empty), even if it is the same map with the same layers (just the extant change).
I'm working with the beta 5, and the legend work well on refreshing when I show/hide layers.
Any idea? Maybe I must refresh the legend when the extent of the map changes?

**Comment by tomwayson** [comment] 2015-10-19 15:49
@jmrroy any chance you can link to some code (public site, fiddle, plunker, bin, etc.) that reproduces this behavior?

**Comment by jmrroy** [comment] 2015-10-20 18:39
No, I'm very sorry but as I said I work with secure layers and a local database. I just figure out that I got an error in the console :

**Comment by tomwayson** [comment] 2015-10-21 17:05
@jmrroy 

Do you know which version of angular-esri-map.js you are using? Otherwise I can't use those line numbers.

I'm in the middle of a major refactoring effort, so it doesn't make sense for me to try to reproduce the problem, but even then, it's hard for me to tell from the title/description of this issue exactly what you're doing.

The best thing you can do if you need help sooner is to create a plunker/fiddle that demonstrates the problem. You can use different (public) layers if needed.

**Comment by jmrroy** [comment] 2015-10-23 16:56
Hi @tomwayson,
I think my problem come from angular ui-router. For example I have a button that go to an another page with the map, when I click to previous page and re-click to the button, the legend didn't load, I have to refresh the page.
I'm using the beta 5 version. I tried to reload the state with ui-sref-opts="{reload:true}", but it doesn't work.
I'm a newb, maybe there is a simple way to fix that. In your example page there is no problem when going back and reclick the legend example page.

**Comment by tomwayson** [comment] 2015-10-23 17:13
The best thing to do would be to create a minimal plunker that has the exact code from our legend page, only using ui-router instead of ng-router.

**Comment by tomwayson** [comment] 2015-10-23 17:44
This _may_ be something we address when we overhaul the docs pages.See #134

**Comment by jmrroy** [comment] 2015-10-23 20:43
I have created a plunker and it works.... The problem not comes from ui-router but from the layer-options, the legend don't reload the second time when there is layer-options in the esri-feature-layer tag and give this error in the console : 

TypeError: self.setInfoTemplate is not a function
at http://localhost:8080/components/angular-esri-map/dist/angular-esri-map.js:588:30

**Comment by tomwayson** [comment] 2015-10-23 20:45
Great, do you have a link to the plunker so I can take a look?

**Comment by jmrroy** [comment] 2015-10-23 20:56
Here it is : http://plnkr.co/edit/OvFs4OkimZNpZclM400s?p=preview.
It is my first plunker ^^ There is other error in the console, I don't know why but on my app, I have only the error I said before.

**Comment by tomwayson** [comment] 2015-10-23 21:42
Thanks for providing the plunker.

This is looking like a bug. Nothing obvious jumped out a me. I'm not sure why it would work w/ ng-router and not ui-router, but TBH I'm not all that familiar w/ ui-router.

BTW The other error you see ($watchGroup is not defined) is due to the fact that [the minimum supported version of this repo is now Angular 1.3](https://github.com/Esri/angular-esri-map/blob/master/CHANGELOG.md#changed-3). That goes away if you update the version of Angular to 1.3.0.

I forked the plunker and updated to Angular 1.3.0 and also the version of angular-esri-map.js that corresponds to the current master of this repo, and I'm still seeing the error:

http://plnkr.co/edit/O5eW59yc9SpGenESuYvE?p=preview

@jwasil, would you take a look at this? You may be more familiar w/ ui-router than me.

**Comment by jmrroy** [comment] 2015-10-23 21:50
I got the same error in the console on your feature layer example page when I go for the second time on it.

**Comment by jwasil** [comment] 2015-10-24 17:58
@jmrroy and @tomwayson thanks for starting the investigative work and thanks for standing up a plunkr to help troubleshoot.  I have a strong feeling that the actual error regarding setInfoTemplate will go away in the release after your beta5 that you are using, however, there might still be an issue with routing (ui router or ng router) and how the timing of the esriLegend directive itself.  There is definitely a difference in refreshing the page versus navigating to it via a router.  Let me dig into this some more.

**Comment by tomwayson** [comment] 2015-10-26 04:33
@jmrroy 

As @jwasil said, this will be fixed in the next release. We're working on that right now in #133. In the mean time, I've updated the plunker w/ the latest build from that branch and you should see that it works:

http://plnkr.co/edit/O5eW59yc9SpGenESuYvE?p=preview

We [still have a bit of work to do](https://github.com/Esri/angular-esri-map/milestones/Beta%206) before the next release, but I don't think the directive API will change - just shuffling some code around under the hood. Until them, you can use that (unminified) angular-esri-map.js file, or you can follow along w/ that PR and then master (once it's merged) and run the builds yourself to continue to get the latest.

**Comment by jmrroy** [comment] 2015-10-26 08:32
@jwasil and @tomwayson thank you very much. I will work with this new js file until the next release.

**Comment by tomwayson** [comment] 2015-10-26 14:54
@jmrroy great. I'll keep you posted on significant updates.

**Closed** 2015-10-29 13:41 UTC
Labels: bug
