### ISSUE TITLE
New sample page for popups (v2beta2)

### ISSUE THREAD

**Issue by jwasilgeo** [Esri/angular-esri-map#211] opened 2016-01-21 22:05 UTC
Create a new sample page for [popups](https://developers.arcgis.com/javascript/beta/sample-code/get-started-popup/index.html).  This should ideally include:
- [x] test page
- [x] functional tests
- [x] example page in the gh-pages site
- [x] deal with info in comment below

Originates from #194.

**Comment by jwasil** [comment] 2016-01-21 23:47
Popups are not behaving well at all in the example page--it is hard to get a click to open a popup at all. And it also appears that the mapView may not be aware of its true positioning in the DOM (like when scrolling with mousewheel).  This might be exposing something in the angular-esri-map source?

- [ ] More investigation is needed before finishing this issue.

**Comment by MikeMatusz** [comment] 2016-01-27 20:15
I think I may have just run into the same issue, and it looks to be reproducible even without using angular.  Using the [Popup sample](https://developers.arcgis.com/javascript/beta/sample-code/sandbox/sandbox.html?sample=get-started-popup), if you put any top/left margin at all on the viewDiv, the click target is offset by a corresponding amount.  I plan on posting to their forum as soon as my account there gets activated.

**Comment by jwasil** [comment] 2016-01-27 20:28
@MikeMatusz, that's really helpful to know.  Thank you for pointing that out and planning to post to the forum.

**Comment by tomwayson** [comment] 2016-01-29 18:52
Good catch @MikeMatusz. At first I wondered why this wasn't the case for the map embedded in the [popup page itself](https://developers.arcgis.com/javascript/beta/sample-code/get-started-popup/index.html), but then I realized that's an iframe pointing to [a page w/ a full screen map](https://developers.arcgis.com/javascript/beta/sample-code/get-started-popup/live/index.html) (i.e. no offset from body).

I'm guessing this is a known issue, but I've reported it via the feedback link on the popup page.

**Comment by cartofrontdev** [comment] 2016-02-02 23:37
HI All,

I am having the exact same issues with intermittent pop up performance. Feature and Multi-Patch type layers are not performing well at all. I am using the current (3 days ago) angular library with mapview. I did have some success including the "Dojo/domready!" but those result may be anecdotal.

I tried playing with z-index and seeing if the map click events where registering. The click events were registering fine but the popups don't always respond. 

I guess I will keep an eye out on this thread as it has been a MAJOR PAIN for me. I thought I was alone in this issue.

Also anyone is interested in making some easy $$ to help me out on my free lance project, message me, I could really use the help with this library.

Thanks,

Dennis

**Comment by tomwayson** [comment] 2016-02-03 00:41
@cartofrontdev 

@MikeMatusz was correct above. There is a known issue in JSAPI 4.0beta3 with popups when the map does not take up the full viewport.

Are you having pop up issues in full screen maps? If so, and those problems are only happening w/ Angular (i.e you have a sample/fiddle that shows the problems don't happen w/ just the JSAPI) please let us know.

Otherwise, not much we can do in this repo until that the bug is resolved in the JSAPI itself.

Sorry that this has been a problem for you, but you're in beta<sup>2</sup> territory here.

**Comment by cartofrontdev** [comment] 2016-02-03 01:08
I am having trouble with full screen maps and they are only happening with the angular library. 

I know this because I was able to consume feature layers from the esri example for popups by changing the url for the feature layer. For the esri beta popup example, the layer loaded up quickly and popups where immediately responsive.

Using the current angular library, I went head and studied the source for map view and the examples, and to be honest the layers and the maps are fairly stable and responsive, but the popups lag. 

I thought it may have been a styling error where maybe the map was hidden another div or that the map was not responding to click events. Neither was the case, I was able to drag and move the mapview quickly and easily. Putting a listener event on the map also responded with a full event object everytime.

Thank, it is just nice to know someone else is aware of this and working on it. I was really demoralized because I thought I had followed everything so closely. It is frustrating being so close with a fully functioning map and not getting working popups.

The last thing I'll say is that there is some wierdness that happens when I included the dojo/domready call. It makes thing much quick and responsive. I am not sure that this is not perception bias, so I welcome you guys to experiment as well.

Thanks,

Dennis

**Comment by tomwayson** [comment] 2016-02-03 03:57
Can you post/link to any fiddles or examples that reproduce the issue?

**Comment by cartofrontdev** [comment] 2016-02-05 22:27
Tom,

I am still working on the fiddle, I am still playing with the issue, but I come accross something interesting.

I added a click event listener on the view (mapView) to console log the map point, screen point, and graphic.

view.on('click', function (evt) {
                        //prints the map coordinates of the clicked location
                        console.log(evt.mapPoint);
                        //prints the screen coordinates of the clicked location
                        console.log(evt.screenPoint);
                        //the graphic object if a feature is clicked in the view
                        console.log(evt.graphic);
                    });

The when I click on a polygon and it does not show a popup for my feature layer, every time the map point will be populated, but the screen point will be undefined and the graphic will be null..

The other thing is I am using the ng-transclude, to inject my mapView as in the current working library. In order to style the mapView I had not considered using the view.height and view.width properties of the mapview. To size my map I hijack the .esri-view class, which gets injected nested in my transclude div for my directive. My thinking is that since I may not be using the view and height properties correctly that could throw it off.

I did try playing with the view.width and view.height, and removed any styling, but still had issues with the popups.

**Comment by jwasilgeo** [comment] 2016-05-06 22:28
Hi all, I'll be moving to close this issue in a forthcoming pull request and eventual tagged release of v2.0.0 of this repo.

It looks like popups have been updated quite a bit in the new release of Esri JSAPI 4.0.  The behavior really is much better, but they will still appear out of place **if** you don't have a fullscreen view container and there is the ability to vertically scroll.  That is out of the control of this repo, and this has also been logged to the JSAPI feedback team.

@MikeMatusz @cartofrontdev thanks a ton for your input and feedback earlier.

**Closed** 2016-05-08 16:35 UTC
Labels: documentation, tests
